version: '3'

services:
  node1:
    image: aerospike:v1
    container_name: node1
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ../aero-data/data:/opt/aerospike/data
    command: ["asd", "--foreground"]

  node2:
    image: aerospike:v1
    container_name: node2
    ports:
      - "3004:3000"
      - "3005:3001"
      - "3006:3002"
      - "3007:3003"
    volumes:
      - ../aero-data/data:/opt/aerospike/data
    command: ["asd", "--foreground"]

  node3:
    image: aerospike:v1
    container_name: node3
    ports:
      - "3008:3000"
      - "3009:3001"
      - "3010:3002"
      - "3011:3003"
    volumes:
      - ../aero-data/data:/opt/aerospike/data
    command: ["asd", "--foreground"]